// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Rule struct {
	TenantID   string             `json:"tenant_id"`
	RuleID     string             `json:"rule_id"`
	Algorithm  string             `json:"algorithm"`
	LimitCount int64              `json:"limit_count"`
	PeriodSecs int64              `json:"period_secs"`
	Burst      int64              `json:"burst"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
