// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM rules
WHERE tenant_id = $1 AND rule_id = $2
`

type DeleteRuleParams struct {
	TenantID string `json:"tenant_id"`
	RuleID   string `json:"rule_id"`
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRule, arg.TenantID, arg.RuleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRule = `-- name: GetRule :one
SELECT tenant_id, rule_id, algorithm, limit_count, period_secs, burst, created_at, updated_at FROM rules
WHERE tenant_id = $1 AND rule_id = $2
`

type GetRuleParams struct {
	TenantID string `json:"tenant_id"`
	RuleID   string `json:"rule_id"`
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, getRule, arg.TenantID, arg.RuleID)
	var i Rule
	err := row.Scan(
		&i.TenantID,
		&i.RuleID,
		&i.Algorithm,
		&i.LimitCount,
		&i.PeriodSecs,
		&i.Burst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRules = `-- name: ListAllRules :many
SELECT tenant_id, rule_id, algorithm, limit_count, period_secs, burst, created_at, updated_at FROM rules
ORDER BY tenant_id, rule_id
`

func (q *Queries) ListAllRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listAllRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.TenantID,
			&i.RuleID,
			&i.Algorithm,
			&i.LimitCount,
			&i.PeriodSecs,
			&i.Burst,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByTenant = `-- name: ListRulesByTenant :many
SELECT tenant_id, rule_id, algorithm, limit_count, period_secs, burst, created_at, updated_at FROM rules
WHERE tenant_id = $1
ORDER BY rule_id
`

func (q *Queries) ListRulesByTenant(ctx context.Context, tenantID string) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRulesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.TenantID,
			&i.RuleID,
			&i.Algorithm,
			&i.LimitCount,
			&i.PeriodSecs,
			&i.Burst,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRule = `-- name: UpsertRule :one
INSERT INTO rules (tenant_id, rule_id, algorithm, limit_count, period_secs, burst)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, rule_id) DO UPDATE SET
    algorithm   = EXCLUDED.algorithm,
    limit_count = EXCLUDED.limit_count,
    period_secs = EXCLUDED.period_secs,
    burst       = EXCLUDED.burst,
    updated_at  = now()
RETURNING tenant_id, rule_id, algorithm, limit_count, period_secs, burst, created_at, updated_at
`

type UpsertRuleParams struct {
	TenantID   string `json:"tenant_id"`
	RuleID     string `json:"rule_id"`
	Algorithm  string `json:"algorithm"`
	LimitCount int64  `json:"limit_count"`
	PeriodSecs int64  `json:"period_secs"`
	Burst      int64  `json:"burst"`
}

func (q *Queries) UpsertRule(ctx context.Context, arg UpsertRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, upsertRule,
		arg.TenantID,
		arg.RuleID,
		arg.Algorithm,
		arg.LimitCount,
		arg.PeriodSecs,
		arg.Burst,
	)
	var i Rule
	err := row.Scan(
		&i.TenantID,
		&i.RuleID,
		&i.Algorithm,
		&i.LimitCount,
		&i.PeriodSecs,
		&i.Burst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
